# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
import os
# import sys
# sys.path.insert(0, os.path.abspath('.'))


# -- Project information -----------------------------------------------------

project = 'SurfATT'
copyright = '2023, Mijian Xu'
author = 'Mijian Xu'
release = "1.4.0"

# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = ['sphinx.ext.githubpages',
              "sphinx.ext.intersphinx",
              "sphinx_copybutton",
              "sphinx_design",
              "myst_parser",
              "sphinx.ext.mathjax",
              "sphinx.ext.todo",
              "sphinx.ext.viewcode",
              'sphinxcontrib.bibtex',
   # To help you with the upgrade to version 5:
   # "sphinxawesome.deprecated",
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'en'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = []

myst_enable_extensions = [
    "colon_fence",
    "deflist",
]


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = "furo"
html_title = "SurfATT"

html_theme_options = {
    # "sidebar_hide_name": False,
    "light_css_variables": {
        "color-brand-primary": "black",
        # "color-brand-content": "",
        # "color-admonition-background": "orange",
    },
}

html_sidebars = {
    "**": [
        "sidebar/scroll-start.html",
        "sidebar/brand.html",
        "sidebar/search.html",
        "sidebar/navigation.html",
        "sidebar/ethical-ads.html",
        "sidebar/scroll-end.html",
    ]
}
# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

# options for sphinx-copybutton
# https://sphinx-copybutton.readthedocs.io
copybutton_prompt_text = r">>> |\.\.\. |\$ |In \[\d*\]: | {2,5}\.\.\.: | {5,8}: "
copybutton_prompt_is_regexp = True
copybutton_only_copy_prompt_lines = True
copybutton_remove_prompts = True

# options for myst-nb
nb_execution_mode = "cache"

# html_extra_path = []
# html_last_updated_fmt = "%Y 年 %m 月 %d 日"
# html_title = project
# html_css_files = ["custom.css"]

# html_logo = os.path.abspath(os.path.join('.', '_static', 'logo_long.png'))
html_favicon = os.path.abspath(os.path.join('.', '_static', 'favicon.ico'))

html_theme_options = {
    "light_logo": "logo_long.png",
    "dark_logo": "logo_long_dark.png",
}

bibtex_bibfiles = ['_static/refs.bib']
bibtex_reference_style = 'author_year'